# ModelSim Simulation Script Template
# Generated by modelsim-hdl-dev skill
#
# This template shows the standard ModelSim TCL commands for:
# 1. Library creation
# 2. File compilation
# 3. Simulation startup
# 4. Waveform configuration
# 5. Simulation execution
#
# Usage:
#   1. Copy this file to your project's sim/ directory
#   2. Modify the file paths and module names
#   3. Run: vsim -do sim_script.tcl

# ============================================
# 1. Library Setup
# ============================================

# Create work library if it doesn't exist
if {![file exists work]} {
    vlib work
}

# Map work library
vmap work work

# ============================================
# 2. Compile Design Files
# ============================================

# Compile all design files
# Note: Paths are relative to sim/ directory
# Use forward slashes even on Windows

# Design file 1
echo "Compiling design files..."
if {[catch {vlog -work work ../hdl/design/YOUR_MODULE.v}]} {
    echo "ERROR: Failed to compile YOUR_MODULE.v"
    quit -f
}

# Design file 2 (if multiple files)
# if {[catch {vlog -work work ../hdl/design/ANOTHER_MODULE.v}]} {
#     echo "ERROR: Failed to compile ANOTHER_MODULE.v"
#     quit -f
# }

echo "✓ Design compilation successful"

# ============================================
# 3. Compile Testbench
# ============================================

echo "Compiling testbench..."
if {[catch {vlog -work work ../hdl/testbench/YOUR_MODULE_tb.v}]} {
    echo "ERROR: Failed to compile testbench"
    quit -f
}

echo "✓ Testbench compilation successful"

# ============================================
# 4. Start Simulation
# ============================================

echo "Starting simulation..."

# Load the testbench module
# Replace YOUR_MODULE_tb with your actual testbench module name
vsim work.YOUR_MODULE_tb

# Alternative: Start with specific options
# vsim -voptargs=+acc work.YOUR_MODULE_tb  # Enable full visibility
# vsim -novopt work.YOUR_MODULE_tb         # Disable optimization (slower but easier debug)

# ============================================
# 5. Configure $finish Behavior
# ============================================

# Set what happens when testbench calls $finish
# Options:
#   stop  - Stop simulation without dialog (recommended)
#   exit  - Quit ModelSim (default)
#   ask   - Show confirmation dialog
onfinish stop

# ============================================
# 6. Setup Waveform Window
# ============================================

echo "Setting up waveform..."

# Open wave window
view wave

# Add all signals recursively
add wave -r /*

# Alternative: Add signals selectively
# add wave /YOUR_MODULE_tb/clk
# add wave /YOUR_MODULE_tb/rst_n
# add wave /YOUR_MODULE_tb/dut/count
# add wave -radix unsigned /YOUR_MODULE_tb/dut/count  # Display as unsigned decimal

# Configure wave window appearance
configure wave -namecolwidth 250      # Width of signal names column
configure wave -valuecolwidth 100     # Width of values column
configure wave -timelineunits ns      # Time units (ns, us, ms, etc.)
configure wave -signalnamewidth 1     # Auto-adjust signal name width

# ============================================
# 7. Run Simulation
# ============================================

echo "Running simulation..."

# Run for specified time
# Adjust based on your testbench requirements
run 1us

# Alternative time specifications:
# run 100ns   # 100 nanoseconds
# run 10us    # 10 microseconds
# run 1ms     # 1 millisecond
# run -all    # Run until $finish (use with caution)

echo "✓ Simulation complete"

# ============================================
# 8. Display Waveform
# ============================================

# Zoom to fit all data
wave zoom full

# Bring wave window to front
view wave
raise .main_pane.wave

# Alternative zoom options:
# wave zoom range 0ns 500ns           # Zoom to specific range
# wave zoom in                        # Zoom in
# wave zoom out                       # Zoom out

# ============================================
# 9. Optional: Save Waveform Configuration
# ============================================

# Save current wave format for future use
# do wave_format.do

# Or create wave format file manually:
# write format wave -window .main_pane.wave wave_format.do

# ============================================
# 10. Completion Message
# ============================================

echo ""
echo "============================================"
echo "Simulation complete!"
echo "============================================"
echo "- Check waveform window for signal values"
echo "- Check transcript for TEST_RESULT: marker"
echo "- To re-run: restart -f; run 1us"
echo "- To quit: quit -f"
echo "============================================"

# ============================================
# Optional: Automatic Result Checking
# ============================================

# You can add TCL code to check for TEST_RESULT automatically:
# proc check_test_result {} {
#     set transcript_file "transcript"
#     if {[file exists $transcript_file]} {
#         set fp [open $transcript_file r]
#         set content [read $fp]
#         close $fp
#
#         if {[string match "*TEST_RESULT: PASS*" $content]} {
#             echo "✓ TEST PASSED"
#             return 1
#         } elseif {[string match "*TEST_RESULT: FAIL*" $content]} {
#             echo "✗ TEST FAILED"
#             return 0
#         }
#     }
#     echo "⚠ No TEST_RESULT found"
#     return 0
# }
#
# check_test_result

# ============================================
# Notes
# ============================================

# Common Issues:
# 1. File not found: Check paths are relative to sim/ directory
# 2. Compilation errors: Check Verilog syntax
# 3. Simulation doesn't stop: Add $finish to testbench
# 4. Waveform empty: Check add wave commands
# 5. Wrong module loaded: Check module name in vsim command

# Tips:
# - Use forward slashes (/) in paths even on Windows
# - Add -work work to vlog commands
# - Use catch {} for error handling
# - Set onfinish stop to avoid dialogs
# - Add TEST_RESULT: markers for automation

# For more help:
# - ModelSim User Manual: Chapter 3 (Compilation)
# - ModelSim User Manual: Chapter 4 (Simulation)
# - ModelSim Command Reference: vlog, vsim, wave commands
