// Testbench for pulse_generator module
// Verifies that pulse is generated every 1ms with 1MHz clock
// Generated by Claude Code
// Date: 2026-01-14

`timescale 1ns/1ps

module pulse_generator_tb;

    // Clock and reset
    reg clk;
    reg rst_n;
    wire pulse_out;

    // Pulse detection
    integer pulse_count;
    integer last_pulse_time;
    integer current_pulse_time;
    integer pulse_interval;
    reg test_passed;

    // Instantiate the pulse generator
    pulse_generator dut (
        .clk(clk),
        .rst_n(rst_n),
        .pulse_out(pulse_out)
    );

    // Clock generation: 1MHz = 1us period = 1000ns
    initial begin
        clk = 0;
        forever #500 clk = ~clk;  // Toggle every 500ns = 1000ns period = 1MHz
    end

    // Monitor pulses
    always @(posedge clk) begin
        if (pulse_out && rst_n) begin
            pulse_count = pulse_count + 1;
            current_pulse_time = $time;

            if (pulse_count > 1) begin
                pulse_interval = current_pulse_time - last_pulse_time;
                $display("Time: %0t ns - Pulse #%0d detected (interval: %0t ns = %0.3f ms)",
                         $time, pulse_count, pulse_interval, pulse_interval / 1000000.0);

                // Check if interval is 1ms (1,000,000 ns)
                if (pulse_interval >= 999000 && pulse_interval <= 1001000) begin
                    $display("  ✓ Interval is correct (~1ms)");
                end else begin
                    $display("  ✗ ERROR: Interval is %0.3f ms (expected 1ms)", pulse_interval / 1000000.0);
                    test_passed = 0;
                end
            end else begin
                $display("Time: %0t ns - First pulse detected", $time);
            end

            last_pulse_time = current_pulse_time;
        end
    end

    // Test sequence
    initial begin
        $display("=== Pulse Generator Testbench Start ===");
        $display("Clock: 1MHz (1us period = 1000ns)");
        $display("Expected: 1 pulse every 1ms (1,000,000 ns)");
        $display("");

        // Initialize
        pulse_count = 0;
        last_pulse_time = 0;
        test_passed = 1;
        rst_n = 0;
        #2000;  // Hold reset for 2us

        // Release reset
        $display("Time: %0t ns - Releasing reset", $time);
        rst_n = 1;

        // Wait for at least 3 pulses (3ms + margin)
        #3500000;  // 3.5ms

        // Test completion
        $display("");
        $display("=== Pulse Generator Testbench Complete ===");
        $display("Total pulses detected: %0d", pulse_count);

        // Check if we got at least 3 pulses
        if (pulse_count >= 3 && test_passed) begin
            $display("TEST_RESULT: PASS - Pulse generator is functioning correctly (%0d pulses in ~3ms)", pulse_count);
        end else if (pulse_count < 3) begin
            $display("TEST_RESULT: FAIL - Only %0d pulses detected (expected at least 3)", pulse_count);
        end else begin
            $display("TEST_RESULT: FAIL - Pulse intervals are incorrect");
        end

        $finish;
    end

    // Watchdog timer (10ms)
    initial begin
        #10000000;
        $display("ERROR: Testbench timeout after 10ms!");
        $display("TEST_RESULT: FAIL - Timeout");
        $finish;
    end

endmodule
