// Pulse Generator Module
// Generates 1 pulse every 1ms with 1MHz clock
// Generated by Claude Code
// Date: 2026-01-14

module pulse_generator (
    input wire clk,        // 1MHz clock
    input wire rst_n,      // Active-low reset
    output reg pulse_out   // Output pulse (1 pulse every 1ms)
);

    // 1MHz clock = 1us period
    // 1ms = 1000us = 1000 clock cycles
    localparam COUNT_MAX = 1000;

    reg [9:0] counter;  // 10 bits can count up to 1023

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // Reset: clear counter and pulse output
            counter <= 10'd0;
            pulse_out <= 1'b0;
        end else begin
            if (counter == COUNT_MAX - 1) begin
                // Reached 1ms, generate pulse
                counter <= 10'd0;
                pulse_out <= 1'b1;
            end else begin
                // Increment counter
                counter <= counter + 1'b1;
                pulse_out <= 1'b0;
            end
        end
    end

endmodule
