// PWM Generator Module
// Generates PWM signal with 8-bit resolution (0-255)
// Generated by Claude Code
// Date: 2026-01-17

module pwm_generator (
    input wire clk,           // 10MHz clock
    input wire rst,           // Synchronous, active-high reset
    input wire [7:0] duty,    // Duty cycle setting (0-255)
    output reg pwm_out        // PWM output signal
);

    // 8-bit free-running counter
    // Counts from 0 to 255, then wraps to 0
    // Period = 256 clock cycles = 25.6us at 10MHz
    // Frequency = 39.06kHz
    reg [7:0] counter;

    // Sequential logic: counter and PWM output
    always @(posedge clk) begin
        if (rst) begin
            // Synchronous reset: clear counter and output
            counter <= 8'd0;
            pwm_out <= 1'b0;
        end else begin
            // Increment counter (wraps automatically at 256)
            counter <= counter + 8'd1;

            // PWM comparison logic
            // Output is HIGH when counter < duty
            // Output is LOW when counter >= duty
            pwm_out <= (counter < duty);
        end
    end

endmodule
